### PR TITLE
INC-5312 - Missing image

### PR DESCRIPTION
**Pull request by gautambhat**
# Description

Fixed broken images showing up in the product catalog for items added without an image url.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks gautambhat, I'll review the changes right away!

**Comment by gautambhat** [comment]
image
image

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job gautambhat! You're now able to merge the PR.

**Pull request merged**
